# -*- coding: utf-8 -*-
"""Naive_bayesian_classifier(7).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OlGMbcMg9v5vKRvOjOmWvFmLMJdC0e8W

# Write a program to implement naive bayesian classifier using sample data from csv file. compute accuracy of the classifier.
"""

import numpy as np
import pandas as pd

df=pd.read_csv("ml_7.csv")
df

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['WC']= label_encoder.fit_transform(df['WC'])
df['HU']= label_encoder.fit_transform(df['HU'])
df['WT']= label_encoder.fit_transform(df['WT'])
df['WC'].unique()
df['HU'].unique()
df['WT'].unique()
df

x=df.iloc[:,:-1]
y=df.iloc[:,4]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)



y_pred=gnb.predict(x_test)
y_pred

from sklearn import  metrics
print("Naive Bayesian accuracy is :",metrics.accuracy_score(y_test,y_pred)*100)

